[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["Jens Lücke"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.37.1"
openai = "^1.42.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
